---
- name: "Create isucon group"
  group:
    name: isucon
    gid: 1100
    state: present
    system: no

- name: "Create isucon user"
  user:
    name: isucon
    uid: 1100
    group: isucon
    password: $1$SALTsalt$e7jg2tj3sKVpmYXXmivBb0
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

#- name: "Create isucon-admin group"
#  group:
#    name: isucon-admin
#    gid: 1200
#    state: present
#    system: no
#
#- name: "Create isucon-admin user"
#  user:
#    name: isucon-admin
#    uid: 1200
#    group: isucon-admin
#    password: $1$SALTsalt$e7jg2tj3sKVpmYXXmivBb0
#    home: /home/isucon-admin
#    shell: /bin/bash
#    state: present
#    system: no
#
#- name: "Create /home/isucon-admin/.ssh directory"
#  file:
#    path: /home/isucon-admin/.ssh
#    state: directory
#    owner: isucon-admin
#    group: isucon-admin
#    mode: 0700
#
#- name: "Add isucon-admin authorized_keys"
#  copy:
#    content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKq/L7EBVcP00sWi1Z4uAo4K9ToLiI59CbknMDtmXj2o isucon-admin@isucon11-final\n"
#    dest: /home/isucon-admin/.ssh/authorized_keys
#    owner: isucon-admin
#    group: isucon-admin
#    mode: 0600

- name: "Add sudoers"
  copy:
    content: |
      isucon        ALL=(ALL) NOPASSWD:ALL
#      isucon-admin  ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/99-isucon-user
    owner: root
    group: root
    mode: 0440

- name: "Copy REVISION"
  copy:
    src: /dev/shm/files-generated/REVISION
    dest: /etc/REVISION
    owner: root
    group: root
    mode: 0644

- name: "Create /tmp/isucon11-final directory"
  file:
    path: /tmp/isucon11-final
    state: directory

- name: "Unarchive isucon11-final.tar"
  unarchive:
    src: /dev/shm/files-generated/isucon11-final.tar
    dest: /tmp/isucon11-final/
    owner: isucon
    group: isucon

- name: "Install packages"
  apt:
    name:
    - libssl-dev
    - libreadline-dev
    - gcc
    - make
    - libffi-dev
    - zlib1g-dev
    - unzip
    - pkg-config
    - autoconf
    - automake
    - build-essential
    - libxml2-dev
    - libsqlite3-dev
    - libbz2-dev
    - libkrb5-dev
    - libcurl4-openssl-dev
    - libpng-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libc-client2007e-dev
    - libxslt-dev
    - libonig-dev
    - libtidy-dev
    - libzip-dev
    - default-mysql-client
    - default-libmysqlclient-dev
    - acl
    - git
    - curl
    update_cache: yes

- name: Install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /tmp/xbuild
    version: master

- name: "Purge snapd"
  become: yes
  become_user: root
  apt:
    name:
    - snap
    - snapd
    state: absent
    purge: yes
