---
- name: "common roles"
  hosts: all
  tags:
    - contestant
    - bench
    - standalone
  become: true
  roles:
    - common
    - certificates

- name: "contestant roles"
  hosts: [contestant, standalone]
  tags: [contestant, standalone]
  become: true
  roles:
    - langs.go
    - langs.rust
    - langs.nodejs
    - langs.ruby
    - langs.php
    - contestant

- name: "bench roles"
  hosts: [bench, standalone]
  tags: [bench, standalone]
  become: true
  roles:
    - bench
    # - bench.node_exporter
    # - bench.supervisor
